---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    # cert-manager.io/issue-temporary-certificate: "true"
    nginx.ingress.kubernetes.io/custom-http-errors: "503"
    nginx.ingress.kubernetes.io/default-backend: {{.Values.error_pages.service.name}}
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    nginx.ingress.kubernetes.io/client-body-buffer-size:  "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    {{ if .Values.ssl.force_redirect }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{ end }}
  name: optscale
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: bernard-testing.fusiondemos.lucidworkstest.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.auth.service.name }}
            port: 
              number: {{ .Values.auth.service.externalPort }}
        path: /auth
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.rest_api.service.name }}
            port: 
              number: {{ .Values.rest_api.service.externalPort }}
        path: /restapi
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.keeper.service.name }}
            port: 
              number: {{ .Values.keeper.service.externalPort }}
        path: /report
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.ngui.service.name }}
            port: 
              number: {{ .Values.ngui.service.externalPort }}
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.herald.service.name }}
            port: 
              number: {{ .Values.herald.service.externalPort }}
        path: /herald
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.katara_service.service.name }}
            port: 
              number: {{ .Values.katara_service.service.externalPort }}
        path: /katara
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.insider_api.service.name }}
            port: 
              number: {{ .Values.insider_api.service.externalPort }}
        path: /insider
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.slacker.service.name }}
            port: 
              number: {{ .Values.slacker.service.externalPort }}
        path: /slacker
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.metroculus_api.service.name }}
            port: 
              number: {{ .Values.metroculus_api.service.externalPort }}
        path: /metroculus
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.jira_bus.service.name }}
            port: 
              number: {{ .Values.jira_bus.service.externalPort }}
        path: /jira_bus
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.jira_ui.service.name }}
            port: 
              number: {{ .Values.jira_ui.service.externalPort }}
        path: /jira_ui
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.diproxy.service.name }}
            port: 
              number: {{ .Values.diproxy.service.externalPort }}
        path: /storage
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.pharos_receiver.service.name }}
            port: 
              number: {{ .Values.pharos_receiver.service.externalPort }}
        path: /pharos_receiver
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.ohsu.service.name }}
            port: 
              number: {{ .Values.ohsu.service.externalPort }}
        path: /ohsu
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.arcee.service.name }}
            port: 
              number: {{ .Values.arcee.service.externalPort }}
        path: /arcee
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.bulldozer_api.service.name }}
            port: 
              number: {{ .Values.bulldozer_api.service.externalPort }}
        path: /bulldozer
        pathType: ImplementationSpecific
  tls:
  - hosts:
      - bernard-testing.fusiondemos.lucidworkstest.com
    secretName:  "optscale-tls-secret"
